apiVersion: v1
kind: Secret
metadata:
    name: umami
    namespace: umami
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:qtNpYG90dsK3gvMlNrcrmwMXC5mh6XihrtO15cCOH9GGVTVqMykIG91aSnD8vXVlPSCwxS3UsJfAECZi5Oe15xCPB4zoidS9Kt7jNwZ8F/ZahdPUQT62FQm8DbSCGBhgjT+i,iv:wp4AkVASsPlvKU2QHsEvrWdbt2vQ2WQHFBJ3OHZV/Xo=,tag:9scRY1vKc80Ykcro3LwpQw==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:sXOAr0Ir531PkHAWtSnrppfqFKnqVNfrV4KYXcY9B5GRAU7ZX1WSVGOQlA9pJmhA,iv:vt8w/c81m8UIwq6VhlRgBGPqZWXTm58+v4gB29mifZ8=,tag:AyDIfGrwy5q8n6sJo+I+TQ==,type:str]
    TWO_FACTOR_ENCRYPTION_KEY: ENC[AES256_GCM,data:P/1QE8HiR9V1GHYJOgqiZSH0e2tG4P7OlP5upqOHSr9Wj6HowThOzwwpG30ilhz0VJqhNPeJ20TZBV9fOfGTvw==,iv:UaZJKaAgmrF1JMvT2BahVVGcBzR8z1faF1qWY3pX6UE=,tag:Tlk3bhDPGBYTRdTnneywog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObllGU2tPOHpDNG9Mc0VO
            QXZCUmI0VTVwUDdPTXZKYkoyK2ZZbzJSS1NBCmtkRytQMmdXNkhyK25DWTloSnYw
            M0hMbmZudjZ1aXB1WDNsTUhRSGJDa00KLS0tIFFWOVgvZkpJNWtLZjdpM0syeSti
            MFJ1Ly9kYTlaL0tQYlBqRFBYRlo0cTgKG7Pa4iFfp+7qRz8CUgOh1HvjFehTPktc
            EYRBGayoN8necReXY5QPU7aRAX8OgQK8Grbj/fK/dgPOvW5JNH98Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3cum0ds099r83vv5ffndhmzr5y5xnk7nk3ja2s7s32ce9gdmppsyrh44w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:36:55Z"
    mac: ENC[AES256_GCM,data:Ho9uhUnyNoxxmTTci66ccRol3e76hnwVvUrKSjKHXxoAiIa703JX6+j3ofdjC/Fkc1vkWLp3oSAEjgYead3nOtmCW63P9TgcDb1KFkIsnOyjv05q3UhF18ZWcAxuoLcoBk5/ZjiaEyQ6Kh7AMXV41xbF+py+fEEnIOhgDmNNbcI=,iv:zar6Bb9s0em2DJCPeVveUEun7+e437Ui3MukZy757Tk=,tag:S7T6hZ2k36G2VzUw3NdIVA==,type:str]
    version: 3.13.3
