apiVersion: v1
kind: Secret
metadata:
    name: bugsink
    namespace: bugsink
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:7TVB8Ro2grKL/8WMNqgGBR83HLN030Zb3GqzaUleQrwSqMJIVEH8gwh3l5PRm4vsM/X8OiK3t2ac7hScU/V0egGc/BH/T9q8v9eG1JZ4tO1gvofhxaQTqIwQj9do8XXjskStjHuWVg==,iv:hkgW3f3rtr/XSBhesRrslRtRwDspFNCtEM58Fx7GJ2U=,tag:aMubE4b/ayCVwW8shp3msA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:c2pMaOBN1BZ5BRacOEChWRwKsnUTQ5OG5JkIJzOm4S7NitxjYtA6bgDwUISYTQTfOjOQYmC4qunPQdqc,iv:kwU3sJYYVcvtfF8yeXYatwDHsXgDvRRKuf+9B9VkYSw=,tag:Muprx6BfnYfnYPJ/R/rFrA==,type:str]
    CREATE_SUPERUSER: ENC[AES256_GCM,data:RTM0V5NFkeour++Yj4PzmJLw9rEhrnVoYmTpn9kQrH1wXW9EgIm9yaZkEpSROQ==,iv:GZfzhrrIHLJ5lGq45AyyvM5q6q++5FZl32AuAPGhpcY=,tag:W8B10udrlZCQDAXzFCxjQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUGNnaURMb3YwZmJIQnNn
            Z1B2L3U4YmlkMnMrUXpGOG9yS1RIbUlUS0FnCk4vbnEzVExINUpkcjQwQ0lScHdZ
            dWUwZGp3ZHFvUkNFMlZRbU82R3laS1kKLS0tIGc1L0ZSVXJlR2l6eDRxRmlHUHVr
            MzQ5cER6VTFaQnErQXFYR0g2V0ZlL3cK2FCgPUQ1DsSPH+aucVPufjJCJnWdjaxa
            B48zi4awVCIOa+vJgDXlU6R0+84GmSFkieufBB26zaszDvhfdchZRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q3cum0ds099r83vv5ffndhmzr5y5xnk7nk3ja2s7s32ce9gdmppsyrh44w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:36:55Z"
    mac: ENC[AES256_GCM,data:tglvGz0jXH3lqFIt1kVuG6jzyBiOB1X2Gk1W+0d4czvNpGN4edSgVTWavtPArRLLdoHvzH9fvYbc2+7C9hpLq+sYkNoMFdRqFmEgw/aLn6pldkrI/abbqLFaw/1wtwhMwFSBkwPXChhVmtrFjjVVrT0pq2hv7kWureB7qlpvW1s=,iv:/0RZl8RhRBrDpE8brisnRAjjf4Hy5x1uBzFq2BK2SRg=,tag:j+HwND69Fz5Vdcepb6stSg==,type:str]
    version: 3.13.3
